//! Auto Generated by the Pulsar Blueprint Editor
//! DO NOT EDIT MANUALLY - YOUR CHANGES WILL BE OVERWRITTEN
//! Generated on 2025-10-08 15:46:03 - Engine version 0.1.30
//!
//! This file contains the main event.
//! To modify this event, open the class in the Pulsar Blueprint Editor
//! and make your changes visually in the node graph.
//!
//! EDITING ANYTHING IN THIS FILE COULD BREAK THE EDITOR
//! AND PREVENT THE GUI FROM OPENING THIS CLASS - BE CAREFUL

use pulsar_std::*;
use super::super::vars::*;

pub fn main() {
    let node_1144a203_567d_4d70_8f2f_2d30f5efc8d1_result = runlua(templateLua());
    println(node_1144a203_567d_4d70_8f2f_2d30f5efc8d1_result.1);
}