//! Auto Generated by the Pulsar blueprint editor
//! DO NOT EDIT MANUALLY - YOUR CHANGES WILL BE OVERWRITTEN
//! Generated on 2024-06-24 16:23:21 - Engine version 0.1.9
//!
//! This file contains the variables for the ExampleClass class
//! you can modify the values here to change the default values
//! of the variables when an instance of this class is created
//! in game. To add or remove variables, open the ExampleClass
//! in the Pulsar blueprint editor and make your changes in the
//! left sidebar.
//!
//! EDITING ANYTHING ELSE IN THIS FILE COULD BREAK THE ENDITOR
//! AND PREVENT THE GUI FROM OPENING THIS CLASS - BE CAREFUL
