//! Auto Generated by the Pulsar blueprint editor
//! DO NOT EDIT MANUALLY - YOUR CHANGES WILL BE OVERWRITTEN
//! Generated on 2024-06-24 16:23:21 - Engine version 0.1.9
//!
//! This file serves as the entry point for the generated game
//! project

use pulsar_std::*;

pub fn main() {

}