//! Auto Generated by the Pulsar Blueprint Editor
//! DO NOT EDIT MANUALLY - YOUR CHANGES WILL BE OVERWRITTEN
//! Generated on 2025-10-13 22:31:57 - Engine version 0.1.34
//!
//! This file contains the begin_play event.
//! To modify this event, open the class in the Pulsar Blueprint Editor
//! and make your changes visually in the node graph.
//!
//! EDITING ANYTHING IN THIS FILE COULD BREAK THE EDITOR
//! AND PREVENT THE GUI FROM OPENING THIS CLASS - BE CAREFUL

use pulsar_std::*;
use super::super::vars::*;

pub fn begin_play() {
    let lua_runtime = Lua :: new () ; let output : Result < String > = lua_runtime . load (templateLua ()) . eval () ; return output . unwrap ()
}
