//! Auto Generated by the Pulsar Blueprint Editor
//! DO NOT EDIT MANUALLY - YOUR CHANGES WILL BE OVERWRITTEN
//! Generated on 2025-10-02 10:25:30 - Engine version 0.1.11
//!
//! This file contains the main event.
//! To modify this event, open the class in the Pulsar Blueprint Editor
//! and make your changes visually in the node graph.
//!
//! EDITING ANYTHING IN THIS FILE COULD BREAK THE EDITOR
//! AND PREVENT THE GUI FROM OPENING THIS CLASS - BE CAREFUL

use pulsar_std::*;

pub fn main() {
    if node_dcf02495_0e52_439e_8e2d_8c0d69a86ff9_result { exec_output ! ("A") ; } else { exec_output ! ("B") ; }
}
