//! Auto Generated by the Pulsar Blueprint Editor
//! DO NOT EDIT MANUALLY - YOUR CHANGES WILL BE OVERWRITTEN
//! Generated on 2025-10-13 22:31:57 - Engine version 0.1.34
//!
//! This file contains the main event.
//! To modify this event, open the class in the Pulsar Blueprint Editor
//! and make your changes visually in the node graph.
//!
//! EDITING ANYTHING IN THIS FILE COULD BREAK THE EDITOR
//! AND PREVENT THE GUI FROM OPENING THIS CLASS - BE CAREFUL

use pulsar_std::*;
use super::super::vars::*;

pub fn main() {
    DSFASDF.with(|v| *v.borrow_mut() = DSFASDF.with(|v| v.borrow().clone()));
    if greater_than (add (2 , 3) , 3) { print_string ("Result is greater than 3! \u{2713}") ; } else { print_string ("Result is 3 or less. \u{2717}") ; }
}
