//! Auto Generated by the Pulsar blueprint editor
//! DO NOT EDIT MANUALLY - YOUR CHANGES WILL BE OVERWRITTEN
//! Generated on 2024-06-24 16:23:21 - Engine version 0.1.9
//!
//! This file serves as the main module for the ExampleClass class
//! and includes its variables and event handlers that define its
//! behavior in the game.

pub mod vars;
pub mod events;

#[derive(Debug, Default)]
pub struct ExampleClass {

}
