//! Auto Generated by the Pulsar Blueprint Editor
//! DO NOT EDIT MANUALLY - YOUR CHANGES WILL BE OVERWRITTEN
//! Generated on 2025-10-01 22:43:09 - Engine version 0.1.9
//!
//! This file contains the begin_play event.
//! To modify this event, open the class in the Pulsar Blueprint Editor
//! and make your changes visually in the node graph.
//!
//! EDITING ANYTHING IN THIS FILE COULD BREAK THE EDITOR
//! AND PREVENT THE GUI FROM OPENING THIS CLASS - BE CAREFUL

use pulsar_std::*;

pub fn begin_play() {
    print_string(Default::default());
    if node_9a6bcef6_8c5b_482d_9ac4_686db736b5e0_result { print_string (Default :: default ()) ; } else { }
}
